import { Router, type IRouter } from "express";
import healthRouter from "./health";
import nflRouter from "./nfl";
import dashboardRouter from "./dashboard";
import settingsRouter from "./settings";
import dataSyncRouter from "./data-sync";
import featuresRouter from "./features";
import authRouter from "./auth";
import consumerRouter from "./consumer";
import consumerPicksRouter from "./consumer-picks";
import consumerTrackingRouter from "./consumer-tracking";
import consumerTeamAnalyticsRouter from "./consumer-team-analytics";
import usageAnalyticsRouter from "./usage-analytics";
import playerProjectionsRouter from "./player-projections";
import gameAlertsRouter from "./game-alerts";
import userPicksRouter from "./user-picks";
import verifiedImageryRouter from "./verified-imagery";

const router: IRouter = Router();

router.use(healthRouter);
router.use(nflRouter);
router.use(dashboardRouter);
router.use(settingsRouter);
router.use(dataSyncRouter);
router.use(featuresRouter);
router.use(authRouter);
router.use(consumerRouter);
router.use(consumerPicksRouter);
router.use(consumerTrackingRouter);
router.use(consumerTeamAnalyticsRouter);
router.use(usageAnalyticsRouter);
router.use(playerProjectionsRouter);
router.use(gameAlertsRouter);
router.use(userPicksRouter);
router.use(verifiedImageryRouter);
export default router;
